WITH 
T1 AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY FK.CONSTRAINT_SCHEMA, FK.CONSTRAINT_NAME) AS RN,
		FK.TABLE_SCHEMA AS child_table_schema,
		FK.TABLE_NAME AS child_table_name,
        FK.TABLE_SCHEMA + '.' + FK.TABLE_NAME AS CHILD_TABLE_FULL_NAME,
        FK.CONSTRAINT_SCHEMA + '.' + FK.CONSTRAINT_NAME AS FOREIGN_KEY_FULL_NAME,
        STRING_AGG(FKC.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY FKC.ORDINAL_POSITION) AS FOREIGN_COLUMNS
    FROM   
        INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS REF 
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS FK 
            ON FK.CONSTRAINT_SCHEMA = REF.CONSTRAINT_SCHEMA 
            AND FK.CONSTRAINT_NAME = REF.CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS FKC 
            ON FK.CONSTRAINT_SCHEMA = FKC.CONSTRAINT_SCHEMA 
            AND FK.CONSTRAINT_NAME = FKC.CONSTRAINT_NAME
    GROUP BY 
        FK.TABLE_SCHEMA, FK.TABLE_NAME, FK.CONSTRAINT_SCHEMA, FK.CONSTRAINT_NAME
),
T2 AS (
    SELECT 
        ROW_NUMBER() OVER (ORDER BY FK.CONSTRAINT_SCHEMA, FK.CONSTRAINT_NAME) AS RN,
        STRING_AGG(UKC.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY UKC.ORDINAL_POSITION) AS REFERENCE_COLUMNS,
        UK.CONSTRAINT_SCHEMA + '.' + UK.CONSTRAINT_NAME AS REFERENCE_CONSTRAINT_FULL_NAME,
		UK.TABLE_SCHEMA AS reference_table_schema,
		UK.TABLE_NAME AS reference_table_name,
        UK.TABLE_SCHEMA + '.' + UK.TABLE_NAME AS REFERENCE_TABLE_FULL_NAME,
        UK.CONSTRAINT_TYPE AS UNIQUE_CONSTRAINT_TYPE_REF
    FROM   
        INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS REF 
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS FK 
            ON FK.CONSTRAINT_SCHEMA = REF.CONSTRAINT_SCHEMA 
            AND FK.CONSTRAINT_NAME = REF.CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS UK 
            ON UK.CONSTRAINT_SCHEMA = REF.UNIQUE_CONSTRAINT_SCHEMA 
            AND UK.CONSTRAINT_NAME = REF.UNIQUE_CONSTRAINT_NAME
        JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS UKC 
            ON UK.CONSTRAINT_SCHEMA = UKC.CONSTRAINT_SCHEMA 
            AND UK.CONSTRAINT_NAME = UKC.CONSTRAINT_NAME
    GROUP BY 
        UK.CONSTRAINT_SCHEMA, UK.CONSTRAINT_NAME, UK.CONSTRAINT_TYPE, UK.TABLE_SCHEMA, UK.TABLE_NAME,
        FK.CONSTRAINT_SCHEMA, FK.CONSTRAINT_NAME
)
SELECT 
	child_table_schema,
	child_table_name,
    CHILD_TABLE_FULL_NAME, 
    FOREIGN_COLUMNS, 
	reference_table_schema,
	reference_table_name,
	REFERENCE_TABLE_FULL_NAME, 
    REFERENCE_COLUMNS,
    UNIQUE_CONSTRAINT_TYPE_REF
FROM   
    T1 
    JOIN T2 ON T1.RN = T2.RN
