SELECT 
    KCU1.TABLE_SCHEMA AS from_table_schema,
    KCU1.TABLE_NAME AS from_table_name ,
    KCU1.COLUMN_NAME AS from_column_name, 
	CONCAT(KCU1.TABLE_SCHEMA, '.', KCU1.TABLE_NAME, '.', KCU1.COLUMN_NAME) AS from_fully_qualified_column,
    KCU2.TABLE_SCHEMA AS to_table_schema,
    KCU2.TABLE_NAME AS to_table_name,
	CONCAT(KCU2.TABLE_SCHEMA, '.', KCU2.TABLE_NAME) AS to_table_full_name,
    KCU2.COLUMN_NAME AS to_table_column,
	CONCAT(KCU2.TABLE_SCHEMA, '.', KCU2.TABLE_NAME, '.', KCU2.COLUMN_NAME) AS to_table_fully_qualified_column
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC 

INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1 
    ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG  
    AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA 
    AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 

INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU2 
    ON KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG  
    AND KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA 
    AND KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME 
    AND KCU2.ORDINAL_POSITION = KCU1.ORDINAL_POSITION 

WHERE 
    CONCAT(KCU1.TABLE_SCHEMA, '.', KCU1.TABLE_NAME, '.', KCU1.COLUMN_NAME) != CONCAT(KCU2.TABLE_SCHEMA, '.', KCU2.TABLE_NAME, '.', KCU2.COLUMN_NAME) -- Edge case: a key referencing itself (shitty db design)